### ISSUE TITLE
MaxReaderSize for wsutil.ReadClientData

### ISSUE THREAD

**Issue by ilovesusu** [gobwas/ws#151] opened 2022-03-08 12:15 UTC
Should you add a max read limit to wsutil.ReadClientData, otherwise, it's hard to use it in production

**Comment by enkeyz** [comment] 2022-04-23 18:47
You can just use https://pkg.go.dev/io#CopyN .

**Comment by Deleplace** [comment] 2022-05-10 11:53
That would be useful indeed. It's mostly about leveraging [Reader.MaxFrameSize](https://github.com/gobwas/ws/blob/master/wsutil/reader.go#L54)

**Comment by cristaloleg** [comment] 2022-05-10 12:19
Can it be solved with https://pkg.go.dev/io#LimitedReader ? as a param to `wsutil.ReadClientData`

**Comment by Deleplace** [comment] 2022-05-10 15:55
Yes actually MaxFrameSize is not what we want here.   

LimitedReader is a better candidate.

**Comment by cristaloleg** [comment] 2023-05-24 14:31
Looks like the issue is resolved, closing. Feel free to reopen, thanks.

**Closed as completed by cristaloleg** 2023-05-24 14:31 UTC
Labels: question
