### ISSUE TITLE
Upgrade request with large cookie header causes ws.ReadHeader to return an EOF error

### ISSUE THREAD

**Issue by jgidlow** [gobwas/ws#32] opened 2018-01-02 16:49 UTC
If you handle a Websocket upgrade request with `ws.Upgrade(conn io.ReadWriter)` and the request has a large cookie header the subsequent call to `ws.ReadHeader(r io.Reader)` will return EOF because `io.ReadFull()` will not read any bytes on the connection.

I don't quite know how to write a repro for this but if you set a large cookie on the same domain that you're connecting to you should be able to reproduce it I think.

**Comment by gobwas** [comment] 2018-01-07 16:25
Hi @jgidlow!

Did you mean that after successful upgrade you want to read WebSocket frame header with `ws.ReadHeader()` and receive `io.EOF` bug?

**Comment by jgidlow** [comment] 2018-01-07 19:20
Hi @gobwas! Hope you're having a great holiday!

Yes, exactly. The upgrade request is successful and it's sending the upgrade response correctly. 

When I tested this I used the "The lower-level example without wsutil" example in the readme file and if the upgrade request contains a large cookie header `ws.ReadHeader()` returns an EOF error here: https://github.com/gobwas/ws/blob/35f877fb85ec2e89544d6130ea6aeec5d628a46b/read.go#L36. I don't understand why it doesn't read any bytes on the connection there though in this case.

If I remove the cookies for the domain the call to `ws.ReadHeader()` is successful.

**Comment by gobwas** [comment] 2018-01-09 21:22
@jgidlow my attempt to reproduce the case currently fails...
Could you give me the code of your upgrade logic?
Maybe you know how to repeat the bug pragmatically without a browser?

**Comment by gobwas** [comment] 2018-01-11 17:33
@jgidlow ping :ping_pong:

**Comment by jgidlow** [comment] 2018-01-13 18:16
Sorry for the delayed answer but I have not been able to reproduce this error again unfortunately so I can't write a repro for it. When the error happened I was using the lower-level example without wsutil from the readme file with the client side code from the test here: https://websocket.org/echo.html.

`ws.ReadHeader()` only returned an EOF error on Firefox in my test then and it was working fine in Chrome. So I tried it in a private window in Firefox and then it started working. So I then cleared the cookies for the domain I was connecting to and then it started working in a normal Firefox window as well. So I assumed it would be easy to reproduce it by just sending a large cookie header in the request but that doesn't seem to be the case. I also didn't save the request data for the request that failed which makes it difficult to figure out what caused this error to happen.

**Comment by gobwas** [comment] 2018-01-14 19:59
Thanks. So I will close the issue for now, because it seems that there is no ability to reproduce it. If you will got the same error, please let me know. 

**FYI** Firefox is the only one browser (according to statistics of an app using `ws`) that could send Ping frames by himself. If you will ignore them, Firefox could close the connection. May be this were the real reason of receiving `io.EOF`?

**Closed by gobwas** 2018-01-14 19:59 UTC
