### ISSUE TITLE
What the correct way to get statusCode for incoming data?

### ISSUE THREAD

**Issue by zebox** [gobwas/ws#39] opened 2018-04-12 20:37 UTC
I'm use your library for implement websocket (with Zero-copy upgrade). I have two object  - Server and Client. 
The Client has handler method **Receive** which listen data for each connection.

```go
func (ch *Channel) Receive(c chan []byte) {
	log.Println("Read client data")
	msg := make([]wsutil.Message, 0, 4)
        

for {
        msg, err := wsutil.ReadClientMessage(ch.conn, msg[:0])
	if err != nil {
		log.Printf("read message error: %v", err)
		return
	}

	for _, m := range msg {

			if m.OpCode.IsControl() {

				// do something for this ...

			}

			if m.OpCode.IsData() {
				statusCode, reason := ws.ParseCloseFrameData(m.Payload)
				log.Printf("Try get statusCode %q, and reason %q", statusCode, reason)

			}
				
		}
  }
}

```
For connect  to my WebSocket server i use Nginx as reverse-proxy and all works fine exclude one moment.
When on the nginx come **proxy_read_timeout** event I can't catch it in my code. After it event i get OpContinuation code and my Receive handler go to infinity loop (that load CPU to 100%).
I tried use **ws.ParseCloseFrameData** function, but payload data has lenght=0 and statusCode=0.

On the other side (web-browser client) gets event 1006  from nginx and browser disconnect properly.

Could you help me. What am I doing wrong?

**Comment by gobwas** [comment] 2018-04-14 08:50
Hi @zebox! When nginx's proxy_read_timeout occur, it just closes both ends of connections – from browser and to your server. So the browser does not receive 1006 code really – it just handles connection close in such way. And, inside your loop you will not receive CloseFrame from nginx too – again, just because it simply close the connection. 

So what we expect your loop to receive is `io.EOF` error.

Could you run this simple example and put it behind your nginx with some proxy_read_timeout set? Something like this:

```go
package main

import (
	"log"
	"net"

	"github.com/gobwas/ws"
	"github.com/gobwas/ws/wsutil"
)

func main() {
	ln, err := net.Listen("tcp", "localhost:8989")
	if err != nil {
		log.Fatal(err)
	}
	for {
		conn, err := ln.Accept()
		if err != nil {
			log.Fatal(err)
		}
		name := conn.RemoteAddr().String()
		log.Printf("accept from %s", name)
		go func() {
			_, err := ws.Upgrade(conn)
			if err != nil {
				log.Printf("upgrade %s error: %v", name, err)
			}
			log.Printf("upgrade %s ok", name)
			for {
				msgs, err := wsutil.ReadClientMessage(conn, nil)
				if err != nil {
					log.Printf("read message from %s error: %v", name, err)
					return
				}
				for _, msg := range msgs {
					log.Printf("received message from %s: %#x", name, msg.OpCode)
				}
			}
		}()
	}
}
```

**Comment by zebox** [comment] 2018-04-14 12:42
I tested nginx as reverse proxy with your code. I set proxy_read_timeout=30s.
`Nginx address is 192.168.56.102:9999 ----reverse-to-ws--> 192.168.56.1:8080`
Debug console output bellow:
```
2018/04/14 15:35:22 accept from 192.168.56.102:51642
2018/04/14 15:35:22 upgrade 192.168.56.102:51642 ok

2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
....
....infinity loop
....
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
2018/04/14 15:33:47 received message from 192.168.56.102:51636: 0x0
...
...
...

```

**Comment by gobwas** [comment] 2018-04-14 16:06
Wow. Looks like a bug currently. I will try to reproduce it tomorrow and investigate deeper in the problem (today I have no good Internet connection 😄).

**Comment by zebox** [comment] 2018-04-14 16:25
Thank you very much! I looking forward to you reply....
Also I tried using gorilla/websocket lib and it got 1006 code from nginx when timeout disconnect .

**Comment by gobwas** [comment] 2018-04-15 21:16
Hi @zebox! The bug has been reproduced and localized. I will think for a while to choose the way how to fix it. Will ping you when it will be fixed. Thanks!

**Comment by zebox** [comment] 2018-04-16 06:11
Good! I will be wait for your fix. Thanks!

**Closed** 2018-04-23 19:48 UTC
Labels: bug
